version: "3.5"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: laravelpassword
      POSTGRES_DB: laravel
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  api:
    hostname: api
    image: api-image
    volumes:
      - ./api:/var/www/html
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:8ULh8JpYt1vUfmzSjm17mjRPu8VTA05YUvW3foSVlts=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: laravelpassword
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
      - ./conf:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - api
    restart: unless-stopped
networks:
  backend:
    driver: bridge
